#!/bin/bash

#if a name is supplied
if [[ $1 ]]; then

    # Check if we nested  within a tmux nession, if so rename 
    if [[ $TMUX ]]
    then
        tmux -L parent rename-window $1
    fi

    #check if there is a session with this name
    count=$(tmux -L children list-sessions | awk -F: '{print $1;}'|grep "^$1$"|wc -l)
    if [[ $count = 1 ]]; then
        #there is such a session. Attach to it
        tmux -L children attach-session -d -t $1
    else
        #there is NO such session. Create it
        tmux -L children new-session -s $1
    fi  

#if no name is supplied give a listing
else
    tmux -L children list-sessions | awk -F: '{print $1;}'
fi

