#!/bin/bash
# Attach to the server "parent" or start it
#

if [ "$1" == "@home" ]; then
 :
elif [ "$1" == "@outandabout" ]; then
 :
elif [ "$1" == "@office" ]; then
 :
else
 echo "accepted locations are @home, @office and @outandabout"
 exit
fi

echo $1 > /tmp/currentlocation

tp="tmux -L parent"
#first just try to attach
$tp attach -d

#if that fails create
if [ $? -eq 1 ]; then
    
    #create the parent session but do not attach to it
    $tp -f ~/tmux/parent new-session -s parent -d 
    
    #$tp new-window -n pomodoro  "tmchild pomodoro" 
    $tp new-window -n pomo
    $tp attach -d
	exit 0;
fi
#sleep 1


